language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t atari59/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true atari59/docker-react npm run test
